name: screen_capturer_windows
description: Windows implementation of the screen_capturer plugin.
version: 0.2.0
repository: https://github.com/leanflutter/screen_capturer/tree/main/packages/screen_capturer_windows
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.0.2
  flutter:
    sdk: flutter
  screen_capturer_platform_interface: 
    git:
      url: https://github.com/yanisalfian/screen_capturer.git
      path: packages/screen_capturer_platform_interface
      ref: main
  win32: '>=2.6.0 <6.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.1

flutter:
  plugin:
    implements: screen_capturer
    platforms:
      windows:
        dartPluginClass: ScreenCapturerWindows
        pluginClass: ScreenCapturerWindowsPluginCApi
